version: "3.8"

services:
  mlflow-proxy:
    container_name: mlflow-proxy
    build:
      context: .
      dockerfile: Dockerfile
    image: mlflow-proxy:latest
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      MLFLOW_UPSTREAM_URL: http://mlflow-oidc:5001
      ADMIN_GROUP_NAME: mlflow-admins
      TOKEN_HEADER_CANDIDATES: authorization,x-forwarded-access-token,x-auth-request-access-token
      REQUEST_TIMEOUT_SECONDS: "60"
      KEYCLOAK_LOGOUT_CLIENT_ID: mlflow-energyguard
      KEYCLOAK_LOGOUT_ID_TOKEN_HEADER_CANDIDATES: x-auth-request-id-token,x-forwarded-id-token,authorization
      KEYCLOAK_LOGOUT_ID_TOKEN_COOKIE_NAME: ""
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME:-}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD:-}
    networks:
      - nginxproxy_energyguard_net

networks:
  nginxproxy_energyguard_net:
    external: true
